<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Argus.Core\Argus.Core.csproj" />
    <ProjectReference Include="..\..\Argus.Ui\Argus.Ui.csproj" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.*" />
    <InternalsVisibleTo Include="ArgusSmoke" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
